services:

  denis:
    container_name: denis-shop
    build: .
    volumes:
      - ./uas-sister:/var/www/html
    ports:
      - 8000:80
  
  mysql_db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: uas-sister
    ports:
    - 3310:3306
  
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 8100:80
    environment:
      - PMA_ARBITRARY=1